[package]
name = "ora-controller"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
ora-node-protocol.workspace = true
ora-utils.workspace = true
ora-logging.workspace = true
tracing.workspace = true
rusqlite = { workspace = true, features = ["bundled"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true
tokio = { workspace = true, features = ["rt", "net", "time", "signal", "macros", "sync"] }

[dev-dependencies]
tempfile.workspace = true
pretty_assertions.workspace = true
